title: A better title will come soon
description: Some analysis of outage data in the US between 2000 and 2016
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one